name: dailyreadings
description: A Flutter app to display the daily readings of the catholic liturgy

publish_to: "none"

version: 1.0.1+7

environment:
  sdk: ">=2.10.0-29 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.14.4
  cupertino_icons: ^1.0.0
  date_util: ^0.1.4
  firebase_analytics: ^6.3.0
  firebase_core: ^0.5.3
  flutter_sfsymbols: ^1.0.0
  flutter_svg: ^0.19.1
  shared_preferences: ^0.5.12+4
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Charter
      fonts:
        - asset: fonts/Charter Regular.ttf
        - asset: fonts/Charter Bold.ttf
          weight: 700
        - asset: fonts/Charter Italic.ttf
          style: italic
        - asset: fonts/Charter Bold Italic.ttf
          weight: 700
          style: italic
    - family: sficonsets
      fonts:
        - asset: packages/flutter_sfsymbols/fonts/sficonsets.ttf
